### ISSUE TITLE
invalid url for `go get`

### ISSUE THREAD

**Issue by fly** [yohcop/openid-go#10]
```
jchen@rousseau> go get github.com/yohcop/openid.go
stat github.com/yohcop/openid.go: no such file or directory
```

https://groups.google.com/forum/?fromgroups#!topic/golang-nuts/dnOK9j5Fvn4

Is it possible to rename this project to openid-go or the like?

**Comment by yohcop** [comment]
Apparently yes.... do you mind trying it?

**Comment by fly** [comment]
well, you would have to do it:

https://help.github.com/articles/renaming-a-repository/

**Comment by yohcop** [comment]
Yeah sorry, I just reverted to actually try before renaming.
I wanted to make sure the name wasn't actually work, given a fair amount of people are using the project.
Renaming again.

**Comment by fly** [comment]
oh, sorry. misunderstood you. In my OP I have an example of what I tried. I also tried the -u flag.

The rename works! GitHub should redirect yohcop/openid.go to yohcop/openid-go until you make another yohcop/openid.go.

Thanks.
