### ISSUE TITLE
Not getting Endpoint from Steam OpenID

### ISSUE THREAD

**Issue by Gacnt** [yohcop/openid-go#11]
I added a `fmt.Println("This is the endpoint: " + endpoint)`

into `nonceStore.go` inside the Accept method

but it prints empty with no value, is this to be expected?

**Comment by yohcop** [comment]
This is very vague.
What is the open ID endpoint for steam?
And what are you calling before this happens, with what parameters? I
assume you are calling openid.RedirectUrl, what are the arguments to this
call?

Thanks,

**Comment by Gacnt** [comment]
Hi, sorry I'm on mobile right now with no access to my code, but it's identical to your _example

Except I use `"http://steamcommunity.com/openid", "http://local host:1337/login/return", "http://local host:1337/"

Because steam requires a realm, your example leaves the third string argument blank. Thanks!!!

**Comment by Gacnt** [comment]
@yohcop Hi there wondering if you ever came up with a reason for this as I still have the same problem, if I run the test provided it logs the end point fine from the accept function, but when I try to use it in production using steam as the provider, with the same information provided above I don't get an endpoint. Thanks.

**Comment by yohcop** [comment]
Unfortunately no. I tried to look at it, but I don't have a steam account so couldn't test much more than that. If anyone figures what the problem is, happy to patch.
