### ISSUE TITLE
How do I verify?

### ISSUE THREAD

**Issue by keitaj** [yohcop/openid-go#18]
https://github.com/yohcop/openid-go/blob/master/_example/server.go#L52-L54

I want here detailed example. In this case, I do not know what to definition in `fullurl` and `discoveryCache`, `nonceStore`.

**Comment by keitaj** [comment]
opEndpoint, opLocalID, claimedID, err := openid.Discover(url)
	query := "?openid.return_to=https://localhost:3000" +
		"&openid.ns=http://specs.openid.net/auth/2.0" +
		"&openid.op_endpoint=" + opEndpoint +
		"&openid.identity=" + opLocalID +
		"&openid.claimed_id=" + claimedID

	openID, err := openid.Verify(url, discoveryCache, nonceStore)
	if err != nil {
		fmt.Println(err) // -> Could not verify that the claimed ID
	}

**Comment by yohcop** [comment]
Sorry, I'm not sure I understand the question.

The nonce store and discovery cache must be long lived objects, and must survive multiple requests (and the same instances must be used for all requests). so I'm not sure how to interpret your example: are you creating the `nonceStore` and `discoveryCache` just before calling Verify?

`fullurl` is the URL where the user was redirected to after authentication.

Hope that helps!

**Comment by strk** [comment]
@keitaj you'll want to use RedirectURL, then you'd get a callback to the URL you specify, and can pass that callback full URL (which would include query params) to the Verify method.

**Comment by yohcop** [comment]
Closing this, it's old now. If you are still having issues, let us know!
