### ISSUE TITLE
Created a package that allows users to use GORM to store their nonce / discovery cache

### ISSUE THREAD

**Issue by Gacnt** [yohcop/openid-go#41]
Sorry for using your issues as a way to do this, but just wondering if you wanted to link to it from your readme or anything, I've created a package https://github.com/Gacnt/gormid so that users can easily use `gorm` to store their nonces / discovery caches in any type of database that `gorm` supports e.g. `mysql/postgres/sqlite` and more.

I also made a SQLX adapter
https://github.com/Gacnt/sqlxid

**Comment by xStrom** [comment]
I just want to note that you haven't bothered to do the very few things that the licence of this library requires you to do. Have a look at [4. Redistribution](http://www.apache.org/licenses/LICENSE-2.0) of the Apache 2.0 licence, under which this library is licensed.

The least you could do is copy-paste the contents of the [LICENCE](https://github.com/yohcop/openid-go/blob/master/LICENSE) file here, and paste it to the bottom of your own LICENCE file, with perhaps adding a simple text header noting that the apache licence is for code taken from openid-go.

**Comment by Gacnt** [comment]
My apologies. New to open source world, licenses and all that stuff

**Comment by yohcop** [comment]
Well, actually I don't think you are redistributing this library in itself, so it's probably fine.

I think the right place to mention/link this project would be on a wiki page. So here it is: https://github.com/yohcop/openid-go/wiki

Thanks!
