### ISSUE TITLE
Does not support link elements with multiple rel values

### ISSUE THREAD

**Issue by adrianheine** [yohcop/openid-go#51]
The example code from [Appendix A.4.  HTML Identifier Markup](https://openid.net/specs/openid-authentication-2_0.html#rfc.section.A.4) doesn't work:

```html
<link rel="openid2.provider openid.server"
      href="http://www.livejournal.com/openid/server.bml"/>
```

**Comment by yohcop** [comment]
Ah, good point!
I'll try to fix this this weekend, unless somebody has a PR before.
Thanks for the report!

**Comment by yohcop** [comment]
Should be fixed now! Sorry for the delay.
